services:
  caddy:
    container_name: caddy
    build:
      context: ./caddy
      no_cache: true
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - 51820:51820/udp # wg uses service:caddy net mode
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy_net
      - tunnel_net

  haproxy:
    container_name: haproxy
    build:
      context: ./haproxy
      no_cache: true
    restart: unless-stopped
    ports:
      - 222:222
    networks:
      - tunnel_net
      - proxy_net

  anubis:
    container_name: anubis
    build:
      context: ./anubis
      no_cache: true
    environment:
      BIND: ":3000"
      TARGET: http://caddy:81
      POLICY_FNAME: "/data/cfg/botPolicy.yaml"
    networks:
      - tunnel_net
      - proxy_net
 
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PEERS=twinkcentre
      - PERSISTENTKEEPALIVE_PEERS=all
    volumes:
      - wireguard_config:/config
    network_mode: service:caddy
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  wireguard_config:

networks:
  proxy_net:
    name: proxy_net
  tunnel_net:
    name: tunnel_net
