services:
  caddy:
    build:
      context: ./caddy
      no_cache: true
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULES
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy_net
      - tunnel_net

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PEERS=twinkcentre
      - PERSISTENTKEEPALIVE_PEERS=all
    volumes:
      - wireguard_config:/config
    ports:
      - 51820:51820/udp
    network_mode: service:caddy
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  wireguard_config:

networks:
  proxy_net:
    name: proxy_net
  tunnel_net:
    name: tunnel_net
