name: Deploy

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Deploy Stack to Host
        uses: ibiixie/stack-deploy-action@feature/multiple-compose-inputs
        env:
          CADDY_EMAIL: ${{ secrets.CADDY_EMAIL }}
          CADDY_EMAIL_PERSONAL: ${{ secrets.CADDY_EMAIL_PERSONAL }}
          DOMAIN_PERSONAL: ${{ secrets.DOMAIN_PERSONAL }}
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          ssh_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          file: ./compose.yaml;./compose.prod.yaml
          name: vps-infra
          mode: compose
