name: Deploy

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Deploy Stack
        uses: cssnr/stack-deploy-action@v1
        with:
          name: infra
          file: compose.yaml compose.prod.yaml
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          ssh_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          mode: compose
          args: --remove-orphans --force-recreate --build
        env:
          CADDY_EMAIL: ${{ secrets.CADDY_EMAIL }}
          CADDY_EMAIL_PERSON: ${{ secrets.CADDY_EMAIL_PERSONAL }}
          DOMAIN_PERSONAL: ${{ secrets.DOMAIN_PERSONAL }}
